# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_myphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myphoto',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='myphoto/%Y/%m/%d/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='myphoto',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
