# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20171019_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='myphoto',
            name='doc',
            field=models.FileField(default='Doc/None/nodc.pdf', upload_to='Doc/'),
        ),
        migrations.AlterField(
            model_name='myphoto',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='myphoto/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='myphoto',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
