# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20171021_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('icon_perfil', models.ImageField(max_length=255, null=True, upload_to='myphoto/%Y/%m/%d/')),
                ('category', models.CharField(max_length=15, verbose_name='Category')),
                ('comment', models.CharField(max_length=500, verbose_name='Comment')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event Coment',
                'verbose_name_plural': 'Event Coments',
            },
        ),
        migrations.RemoveField(
            model_name='myphoto',
            name='doc',
        ),
    ]
