# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20171021_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosPessoais',
        ),
        migrations.DeleteModel(
            name='MyPhoto',
        ),
    ]
