# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20171022_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='eventcomments',
            name='comment',
            field=models.CharField(max_length=250, verbose_name='Comment'),
        ),
    ]
