# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_imagens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagens',
            options={'verbose_name': 'Event Coment', 'verbose_name_plural': 'Event Coments'},
        ),
    ]
