# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_auto_20171025_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='icon_perfil',
            field=models.ImageField(max_length=255, null=True, upload_to='myphoto/%Y/%m/%d/'),
        ),
    ]
