# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_imagens_icon_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagens',
            name='icon_perfil',
        ),
    ]
