# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_auto_20171025_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagens',
        ),
    ]
