# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_delete_imagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomments',
            name='icon_perfil',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
