# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_auto_20171030_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
