# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_auto_20171030_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomments',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
