# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 04:36
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_auto_20171030_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcomments',
            name='comment_time',
        ),
        migrations.AddField(
            model_name='eventcomments',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='eventcomments',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
